name: Gerar readme a partir da issue
on:
  issues:
    types: [opened]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Criar arquivo README
      run: |
        plataform=$(jq --raw-output '.issue.body | match("Qual a plataforma?[^#]*#(.*)") .captures[0].string' $GITHUB_EVENT_PATH | xargs)
        dateString=$(jq --raw-output '.issue.body | match("Data da release[^#]*#(.*)") .captures[0].string' $GITHUB_EVENT_PATH | xargs)
        echo ${plataform}
        echo ${dateString}
        mkdir -p content/pt-br/iniciacao-pagamentos-canais/mobile
        echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g' > content/pt-br/iniciacao-pagamentos-canais/mobile/_${plataform}.md
    - name: Configurar Git
      run: |
        git config --global user.email "${{ github.event.issue.user.email }}"
        git config --global user.name "${{ github.event.issue.user.login }}"
    - name: Commit e push
      run: |
        git add -A
        git commit -m "Adicionar README gerado automaticamente a partir da issue #${{ github.event.issue.number }}"
        git push
