name: Gerar readme a partir da issue
on:
  issues:
    types: [opened]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Criar arquivo README
      run: |
        plataform=$(jq --raw-output '.issue.fields | select(has("plataform")).plataforma' $GITHUB_EVENT_PATH)
        date=$(jq --raw-output '.issue.fields | select(has("date")).plataforma' $GITHUB_EVENT_PATH)
        dateString=$(date -d "${date}" +"%Y-%m-%d")
        echo "${{ github.event.issue.body }}" > content/pt-br/iniciacao-pagamentos-canais/_${plataform}-${dateString}.md

    - name: Configurar Git
      run: |
        git config --global user.email "${{ github.event.issue.user.email }}"
        git config --global user.name "${{ github.event.issue.user.login }}"

    - name: Commit e push
      run: |
        plataforma=$(jq --raw-output '.issue.fields | select(has("plataforma")).plataforma' $GITHUB_EVENT_PATH)
        git add documentacao/README-${plataforma}.md
        git commit -m "Adicionar README gerado automaticamente a partir da issue #${{ github.event.issue.number }}"
        git push
