name: Gerar readme a partir da issue
on:
  issues:
    types: [opened]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Criar arquivo README
      run: |
        echo "${{ github.event.issue.body }}" > README.md

    - name: Configurar Git
      run: |
        git config --global user.email "${{ github.event.issue.user.email }}"
        git config --global user.name "${{ github.event.issue.user.login }}"

    - name: Commit e push
      run: |
        git add README.md
        git commit -m "Adicionar README gerado automaticamente a partir da issue #${{ github.event.issue.number }}"
        git push
