name: Gerar readme a partir da issue
on:
  issues:
    types: [opened]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Criar arquivo README
      run: |
        plataform=$(jq --raw-output '.issue.body' "$GITHUB_EVENT_PATH" | grep -oP '(?<=Qual a plataforma\?\n\n).+' | tr -d '\r')
        dateForm=$(jq --raw-output '.issue.body' "$GITHUB_EVENT_PATH" | grep -oP '(?<=Data da release\n\n).+' | tr -d '\r')        echo ${plataform}
        echo "1"
        echo ${plataform}
        echo "2"        
        echo ${dateForm}
        mkdir -p content/pt-br/iniciacao-pagamentos-canais/mobile
        echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g' > content/pt-br/iniciacao-pagamentos-canais/mobile/_teste.md
    - name: Configurar Git
      run: |
        git config --global user.email "${{ github.event.issue.user.email }}"
        git config --global user.name "${{ github.event.issue.user.login }}"
    - name: Commit e push
      run: |
        git add -A
        git commit -m "Adicionar README gerado automaticamente a partir da issue #${{ github.event.issue.number }}"
        git push
